version: "3.3"

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails s -p ${PORT} -b 0.0.0.0"
    env_file: ".env"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    depends_on:
      - db

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./services/nginx/devops.conf:/etc/nginx/devops.conf"
    depends_on:
      - app

  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
