FROM ruby:2.6.1

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get install -y nodejs
RUN apt-get update && apt-get install -y yarn

ENV PROJECT_ROOT /usr/src/app
ENV BUNDLE_PATH $PROJECT_ROOT/vendor/bundle
ENV GEM_HOME $PROJECT_ROOT/vendor/bundle

WORKDIR $PROJECT_ROOT

RUN yarn
