version: "2"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "bin/rails test"
    depends_on:
      - db
