version: "2"

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "echo 1"
    environment:
      - RAILS_ENV=test
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
