# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: debb25d07bdc38ea10d819f33bb43c261cc5e2c991d18db06aa2fe07fb40ef53ce018512f4ccf6cf261bfd15811f1a787e8f12c9fd5bc022a15360361e3ac8c5

test:
  secret_key_base: dac1447aa1ff5ead2869ec0d5a31759b39c243e88214389de7926e62fa38a246db4dac228220f9545c2fe09494de8965af42226323d11ba8c7157d8667c07734

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
